from __future__ import annotations

import argparse
import sys

from . import __version__
from . import carve_db
from .compare_video_live import run as run_compare_video_live
from .fuse import run as run_fuse
from .plan_restore import run as run_plan_restore
from .restore import run as run_restore
from .snapshot import run as run_snapshot
from .video_ocr import run as run_video_ocr


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="notes-recover", description="Evidence-driven Apple Notes recovery toolkit for macOS.")
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    subparsers = parser.add_subparsers(dest="command", required=True)

    snapshot_parser = subparsers.add_parser("snapshot", help="Back up live Notes database files and export account metadata.")
    snapshot_parser.add_argument("--out-dir", required=True, help="Directory where the snapshot bundle will be written.")
    snapshot_parser.add_argument("--notes-container", default="~/Library/Group Containers/group.com.apple.notes", help="Path to the local Notes group container.")
    snapshot_parser.add_argument("--account", default="iCloud", help="Notes account name.")
    snapshot_parser.add_argument("--folder", default="Recently Deleted", help="Folder to export note titles from.")
    snapshot_parser.add_argument("--folder-manifest-name", default="live_folder_notes", help="Base filename for the exported folder manifest.")
    snapshot_parser.set_defaults(func=run_snapshot)

    carve_parser = subparsers.add_parser("carve-db", help="Best-effort recovery of stale folder mappings from a copied NoteStore.sqlite.")
    carve_parser.add_argument("--db", required=True, help="Path to a copied NoteStore.sqlite.")
    carve_parser.add_argument("--out-dir", required=True, help="Directory for exported mapping files.")
    carve_parser.add_argument("--lookback", type=int, default=1600, help="How far backward from a UUID hit to search for a stale row start.")
    carve_parser.set_defaults(func=carve_db.main)

    video_ocr_parser = subparsers.add_parser("video-ocr", help="Run OCR on a screen recording and emit structured frame text.")
    video_ocr_parser.add_argument("video", help="Path to the input .mov or .mp4 video.")
    video_ocr_parser.add_argument("--interval", type=float, required=True, help="Frame extraction interval in seconds.")
    video_ocr_parser.add_argument("--out-json", required=True, help="Path to the OCR JSON output.")
    video_ocr_parser.add_argument("--build-dir", default=".build", help="Directory for compiling the Swift helper.")
    video_ocr_parser.add_argument("--swift-source", help="Optional path to a custom Swift OCR helper.")
    video_ocr_parser.set_defaults(func=run_video_ocr)

    compare_parser = subparsers.add_parser("compare-video-live", help="Match OCR-derived folder/title pairs against live note titles.")
    compare_parser.add_argument("--ocr-json", required=True, help="Path to OCR JSON generated by video-ocr.")
    compare_parser.add_argument("--live-titles", required=True, help="TSV of live note titles, typically from snapshot.")
    compare_parser.add_argument("--out-dir", required=True, help="Directory for comparison outputs.")
    compare_parser.add_argument("--known-folders", help="TSV of known folder names used to canonicalize OCR output.")
    compare_parser.set_defaults(func=run_compare_video_live)

    fuse_parser = subparsers.add_parser("fuse", help="Merge carving and optional fallback evidence into direct, inferred, and review buckets.")
    fuse_parser.add_argument("--live-titles", required=True, help="TSV of live note titles.")
    fuse_parser.add_argument("--folder-names", required=True, help="TSV of folder names.")
    fuse_parser.add_argument("--video-run-dir", action="append", default=[], help="Optional directory produced by compare-video-live. May be passed multiple times.")
    fuse_parser.add_argument("--mac-mappings", help="TSV produced by carve-db, usually recovered_restorable_mappings.tsv.")
    fuse_parser.add_argument("--residual-folder", help="Optional fallback folder name for residual inference.")
    fuse_parser.add_argument("--expected-residual-count", type=int, help="Optional expected count for the fallback folder.")
    fuse_parser.add_argument("--out-dir", required=True, help="Directory for fused outputs.")
    fuse_parser.set_defaults(func=run_fuse)

    plan_parser = subparsers.add_parser("plan-restore", help="Build a unified restore plan from direct, inferred, and review buckets.")
    plan_parser.add_argument("--direct", required=True, help="TSV of direct evidence assignments.")
    plan_parser.add_argument("--residual", help="TSV of residual bucket inference.")
    plan_parser.add_argument("--review", help="TSV of review-needed assignments.")
    plan_parser.add_argument("--review-folder", default="Recovery Review", help="Folder name for uncertain notes.")
    plan_parser.add_argument("--out", required=True, help="Path to the restore plan TSV.")
    plan_parser.set_defaults(func=run_plan_restore)

    restore_parser = subparsers.add_parser("restore", help="Apply a restore plan to live Notes.")
    restore_parser.add_argument("--plan", required=True, help="Restore plan TSV.")
    restore_parser.add_argument("--account", default="iCloud", help="Notes account name.")
    restore_parser.add_argument("--success-log", required=True, help="Path to the success log TSV.")
    restore_parser.add_argument("--failure-log", required=True, help="Path to the failure log TSV.")
    restore_parser.add_argument("--apply", action="store_true", help="Actually mutate live Notes. Without this flag, the command runs in dry-run mode.")
    restore_parser.set_defaults(func=run_restore)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    func = args.func
    if func is carve_db.main:
        return func(argv=["--db", args.db, "--out-dir", args.out_dir, "--lookback", str(args.lookback)])
    return func(args)


if __name__ == "__main__":
    sys.exit(main())
